apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: customer-api
  namespace: mythical-payment
  labels:
    service-mesh.mulesoft.com/kind: api
spec:
  clusterServiceClassExternalName: anypoint-platform-api-instance
  clusterServicePlanExternalName: service-mesh
  parameters:
    environmentId: <ENV ID>
    assetId: customer-api
    version: 1.0.0
    instanceLabel: public
    tags:
      apiSpec:
      - mythical-payment
      apiInstance:
      - mythical-payment
    user: <USER>
    password: <PASSWORD>
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: inventory-api
  namespace: mythical-payment
  labels:
    service-mesh.mulesoft.com/kind: api
spec:
  clusterServiceClassExternalName: anypoint-platform-api-instance
  clusterServicePlanExternalName: service-mesh
  parameters:
    environmentId: <ENV ID>
    assetId: inventory-api
    version: 1.0.0
    instanceLabel: public
    tags:
      apiSpec:
      - mythical-payment
      apiInstance:
      - mythical-payment
    user: <USER>
    password: <PASSWORD>
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: order-api
  namespace: mythical-payment
  labels:
    service-mesh.mulesoft.com/kind: api
spec:
  clusterServiceClassExternalName: anypoint-platform-api-instance
  clusterServicePlanExternalName: service-mesh
  parameters:
    environmentId: <ENV ID>
    assetId: order-api
    version: 1.0.0
    instanceLabel: public
    tags:
      apiSpec:
      - mythical-payment
      apiInstance:
      - mythical-payment
    user: <USER>
    password: <PASSWORD>
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: payment-api
  namespace: mythical-payment
  labels:
    service-mesh.mulesoft.com/kind: api
spec:
  clusterServiceClassExternalName: anypoint-platform-api-instance
  clusterServicePlanExternalName: service-mesh
  parameters:
    environmentId: <ENV ID>
    assetId: payment-api
    version: 1.0.0
    instanceLabel: public
    tags:
      apiSpec:
      - mythical-payment
      apiInstance:
      - mythical-payment
    user: <USER>
    password: <PASSWORD>
